package com.lexora.service.core.model

enum class SyncState { SYNCED, PENDING_CREATE, PENDING_UPDATE, PENDING_DELETE, ERROR }
enum class ClientType { PERSON, COMPANY }
enum class RequestStatus { NEW, QUALIFICATION, PLANNED, IN_PROGRESS, WAITING, WORK_COMPLETED, CONFIRMATION, CLOSED, CANCELLED }
enum class RequestPriority { LOW, NORMAL, HIGH, URGENT }
enum class RequestChangeType { CREATED, UPDATED, STATUS, ASSIGNMENT, RESCHEDULE, SLA }
enum class VisitStatus { PLANNED, EN_ROUTE, ON_SITE, COMPLETED, CANCELLED }
enum class ChecklistItemState { PENDING, DONE, NOT_APPLICABLE }
enum class ServiceDocumentType { WORK_ORDER, ACT, INVOICE }
enum class ServiceDocumentStatus { DRAFT, ISSUED, SIGNED, CANCELLED }
enum class PaymentStatus { PLANNED, PAID, CANCELLED }
enum class PaymentMethod { CASH, CARD, BANK_TRANSFER, OTHER }
enum class SyncOperationType { CREATE, UPDATE, DELETE }
enum class SyncOperationStatus { PENDING, IN_PROGRESS, RETRY_WAIT, SUCCEEDED, FAILED, CONFLICT }
enum class SyncConflictResolution { UNRESOLVED, KEEP_LOCAL, KEEP_REMOTE, MERGED }
enum class WashPostStatus { AVAILABLE, OCCUPIED, OUT_OF_SERVICE }
enum class WashQueueStatus { WAITING, CALLED, IN_SERVICE, COMPLETED, CANCELLED }
enum class TireQueueStatus { WAITING, CALLED, IN_SERVICE, COMPLETED, CANCELLED }
enum class TireStorageStatus { STORED, ISSUED }
enum class AdditionalWorkApprovalStatus { NOT_REQUIRED, PENDING, APPROVED, REJECTED }
enum class LoyaltyTransactionType { ACCRUAL, REDEMPTION, ADJUSTMENT }
enum class QualityControlStatus { PENDING, PASSED, ISSUE_FOUND, RESOLVED }
enum class ContractStatus { DRAFT, ACTIVE, SUSPENDED, TERMINATED, EXPIRED }

data class Client(val id: String, val organizationId: String, val type: ClientType, val displayName: String, val phone: String? = null, val email: String? = null, val taxId: String? = null, val kpp: String? = null, val registrationAddress: String? = null, val actualAddress: String? = null, val note: String? = null, val consentPersonalData: Boolean = false, val archived: Boolean = false, val syncState: SyncState = SyncState.PENDING_CREATE)
data class Vehicle(val id: String, val organizationId: String, val clientId: String?, val registrationNumber: String, val vin: String? = null, val make: String? = null, val model: String? = null, val year: Int? = null, val bodyType: String? = null, val color: String? = null, val mileageKm: Int? = null, val archived: Boolean = false, val syncState: SyncState = SyncState.PENDING_CREATE)
data class Branch(val id: String, val organizationId: String, val name: String, val address: String? = null, val phone: String? = null, val email: String? = null, val workSchedule: String? = null, val timeZoneId: String, val active: Boolean = true, val syncState: SyncState = SyncState.PENDING_CREATE)
data class Employee(val id: String, val organizationId: String, val branchId: String?, val displayName: String, val position: String? = null, val phone: String? = null, val email: String? = null, val active: Boolean = true, val syncState: SyncState = SyncState.PENDING_CREATE)
data class ServiceObject(val id: String, val organizationId: String, val clientId: String?, val name: String, val address: String? = null, val accessMode: String? = null, val responsibleContact: String? = null, val archived: Boolean = false, val syncState: SyncState = SyncState.PENDING_CREATE)
data class Equipment(val id: String, val organizationId: String, val serviceObjectId: String?, val type: String, val make: String? = null, val model: String? = null, val serialNumber: String? = null, val inventoryNumber: String? = null, val barcode: String? = null, val commissionedNote: String? = null, val warrantyNote: String? = null, val archived: Boolean = false, val syncState: SyncState = SyncState.PENDING_CREATE)
data class ServiceRequest(val id: String, val organizationId: String, val number: String, val clientId: String?, val vehicleId: String? = null, val serviceObjectId: String? = null, val equipmentId: String? = null, val contractId: String? = null, val branchId: String? = null, val assigneeEmployeeId: String? = null, val assigneeTeamName: String? = null, val title: String, val description: String? = null, val status: RequestStatus = RequestStatus.NEW, val priority: RequestPriority = RequestPriority.NORMAL, val plannedAtEpochMs: Long? = null, val plannedEndEpochMs: Long? = null, val dueAtEpochMs: Long? = null, val slaReactionMinutes: Int? = null, val slaResolutionMinutes: Int? = null, val slaWarningMinutes: Int = 30, val slaDeadlineEpochMs: Long? = null, val firstReactionAtEpochMs: Long? = null, val closedAtEpochMs: Long? = null, val archived: Boolean = false, val syncState: SyncState = SyncState.PENDING_CREATE, val createdAtEpochMs: Long = 0, val updatedAtEpochMs: Long = 0)
data class RequestChangeHistory(val id: String, val requestId: String, val type: RequestChangeType, val changedByUserId: String, val changedAtEpochMs: Long, val reason: String? = null, val beforeSummary: String? = null, val afterSummary: String? = null)
data class RequestStatusHistory(val id: String, val requestId: String, val fromStatus: RequestStatus?, val toStatus: RequestStatus, val changedByUserId: String, val changedAtEpochMs: Long, val comment: String? = null)
data class ServiceVisit(val id: String, val organizationId: String, val requestId: String, val branchId: String? = null, val employeeId: String? = null, val status: VisitStatus = VisitStatus.PLANNED, val plannedStartEpochMs: Long? = null, val plannedEndEpochMs: Long? = null, val actualStartEpochMs: Long? = null, val actualEndEpochMs: Long? = null, val resultNote: String? = null, val customerName: String? = null, val customerSignatureRef: String? = null, val syncState: SyncState = SyncState.PENDING_CREATE)
data class VisitChecklistItem(val id: String, val visitId: String, val title: String, val state: ChecklistItemState = ChecklistItemState.PENDING, val comment: String? = null, val sortOrder: Int = 0, val syncState: SyncState = SyncState.PENDING_CREATE)
data class VisitWorkEntry(val id: String, val visitId: String, val serviceCode: String? = null, val title: String, val quantity: Double = 1.0, val unit: String? = null, val note: String? = null, val syncState: SyncState = SyncState.PENDING_CREATE)
data class VisitMaterialUsage(val id: String, val visitId: String, val materialCode: String? = null, val title: String, val quantity: Double, val unit: String? = null, val note: String? = null, val syncState: SyncState = SyncState.PENDING_CREATE)
data class VisitPhoto(val id: String, val visitId: String, val localUri: String, val caption: String? = null, val takenAtEpochMs: Long, val syncState: SyncState = SyncState.PENDING_CREATE)
data class ServiceDocument(val id: String, val organizationId: String, val requestId: String?, val visitId: String?, val clientId: String?, val type: ServiceDocumentType, val number: String, val status: ServiceDocumentStatus = ServiceDocumentStatus.DRAFT, val issuedAtEpochMs: Long? = null, val totalMinor: Long = 0, val currency: String = "RUB", val externalFileRef: String? = null, val note: String? = null, val archived: Boolean = false, val syncState: SyncState = SyncState.PENDING_CREATE)
data class Payment(val id: String, val organizationId: String, val requestId: String?, val documentId: String?, val clientId: String?, val amountMinor: Long, val currency: String = "RUB", val status: PaymentStatus = PaymentStatus.PLANNED, val method: PaymentMethod = PaymentMethod.BANK_TRANSFER, val paidAtEpochMs: Long? = null, val externalReference: String? = null, val note: String? = null, val archived: Boolean = false, val syncState: SyncState = SyncState.PENDING_CREATE)
data class SyncOperation(val id: String, val organizationId: String, val entityType: String, val entityId: String, val operationType: SyncOperationType, val idempotencyKey: String, val payloadJson: String? = null, val status: SyncOperationStatus = SyncOperationStatus.PENDING, val attemptCount: Int = 0, val nextAttemptAtEpochMs: Long? = null, val lastError: String? = null, val createdAtEpochMs: Long, val updatedAtEpochMs: Long)
data class SyncConflict(val id: String, val organizationId: String, val entityType: String, val entityId: String, val localVersionJson: String?, val remoteVersionJson: String?, val resolution: SyncConflictResolution = SyncConflictResolution.UNRESOLVED, val detectedAtEpochMs: Long, val resolvedAtEpochMs: Long? = null)
data class WashPost(val id: String, val organizationId: String, val branchId: String?, val name: String, val status: WashPostStatus = WashPostStatus.AVAILABLE, val active: Boolean = true, val syncState: SyncState = SyncState.PENDING_CREATE)
data class WashQueueItem(val id: String, val organizationId: String, val requestId: String?, val vehicleId: String?, val postId: String?, val position: Int, val status: WashQueueStatus = WashQueueStatus.WAITING, val createdAtEpochMs: Long, val syncState: SyncState = SyncState.PENDING_CREATE)
data class WashTechCard(val id: String, val organizationId: String, val name: String, val durationMinutes: Int, val stepsText: String, val active: Boolean = true, val syncState: SyncState = SyncState.PENDING_CREATE)
data class WashChemicalUsage(val id: String, val organizationId: String, val requestId: String?, val postId: String?, val chemicalName: String, val quantityMl: Double, val usedAtEpochMs: Long, val syncState: SyncState = SyncState.PENDING_CREATE)
data class TireQueueItem(val id: String, val organizationId: String, val requestId: String?, val vehicleId: String?, val position: Int, val status: TireQueueStatus, val createdAtEpochMs: Long, val syncState: SyncState = SyncState.PENDING_CREATE)
data class TireDiagnostic(val id: String, val organizationId: String, val requestId: String?, val vehicleId: String?, val pressureNote: String?, val treadDepthMm: Double?, val damageNote: String?, val recommendation: String?, val diagnosedAtEpochMs: Long, val syncState: SyncState = SyncState.PENDING_CREATE)
data class TireWorkEntry(val id: String, val organizationId: String, val requestId: String?, val vehicleId: String?, val title: String, val quantity: Double, val note: String?, val performedAtEpochMs: Long, val syncState: SyncState = SyncState.PENDING_CREATE)
data class TireStorageItem(val id: String, val organizationId: String, val clientId: String?, val vehicleId: String?, val storageCode: String, val tireDescription: String, val quantity: Int, val location: String?, val status: TireStorageStatus, val storedAtEpochMs: Long, val issuedAtEpochMs: Long?, val syncState: SyncState = SyncState.PENDING_CREATE)
data class ServiceCatalogItem(val id: String, val organizationId: String, val code: String, val name: String, val category: String? = null, val unit: String = "шт.", val durationMinutes: Int? = null, val active: Boolean = true, val syncState: SyncState = SyncState.PENDING_CREATE)
data class PriceList(val id: String, val organizationId: String, val name: String, val currency: String = "RUB", val effectiveFromEpochMs: Long, val effectiveToEpochMs: Long? = null, val active: Boolean = true, val syncState: SyncState = SyncState.PENDING_CREATE)
data class PriceListItem(val id: String, val priceListId: String, val serviceCatalogItemId: String, val priceMinor: Long, val syncState: SyncState = SyncState.PENDING_CREATE)
data class WorkOrderItem(val id: String, val documentId: String, val serviceCatalogItemId: String?, val title: String, val quantity: Double, val unit: String, val unitPriceMinor: Long, val totalMinor: Long, val additional: Boolean = false, val approvalStatus: AdditionalWorkApprovalStatus = AdditionalWorkApprovalStatus.NOT_REQUIRED, val approvalComment: String? = null, val approvedAtEpochMs: Long? = null, val syncState: SyncState = SyncState.PENDING_CREATE)
data class LoyaltyAccount(val id: String, val organizationId: String, val clientId: String, val pointsBalance: Long = 0, val active: Boolean = true, val syncState: SyncState = SyncState.PENDING_CREATE)
data class LoyaltyTransaction(val id: String, val organizationId: String, val clientId: String, val accountId: String, val requestId: String? = null, val paymentId: String? = null, val type: LoyaltyTransactionType, val pointsDelta: Long, val comment: String? = null, val occurredAtEpochMs: Long, val syncState: SyncState = SyncState.PENDING_CREATE)
data class QualityControlRecord(val id: String, val organizationId: String, val requestId: String, val clientId: String? = null, val vehicleId: String? = null, val status: QualityControlStatus = QualityControlStatus.PENDING, val rating: Int? = null, val checklistResult: String? = null, val issueDescription: String? = null, val resolutionNote: String? = null, val controlledAtEpochMs: Long? = null, val syncState: SyncState = SyncState.PENDING_CREATE)
data class ServiceContract(val id: String, val organizationId: String, val clientId: String, val branchId: String? = null, val number: String, val subject: String, val status: ContractStatus = ContractStatus.DRAFT, val startAtEpochMs: Long? = null, val endAtEpochMs: Long? = null, val signedAtEpochMs: Long? = null, val externalFileRef: String? = null, val note: String? = null, val archived: Boolean = false, val syncState: SyncState = SyncState.PENDING_CREATE)
