package com.lexora.service.core.database

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(
    entities = [
        OrganizationEntity::class, ClientEntity::class, VehicleEntity::class, BranchEntity::class,
        EmployeeEntity::class, ModuleSettingEntity::class, AuditEventEntity::class, ServiceHistoryEntity::class,
        ServiceObjectEntity::class, EquipmentEntity::class, ServiceRequestEntity::class, RequestStatusHistoryEntity::class,
        ServiceVisitEntity::class, VisitChecklistItemEntity::class, VisitWorkEntryEntity::class, VisitMaterialUsageEntity::class,
        VisitPhotoEntity::class, ServiceDocumentEntity::class, PaymentEntity::class, SyncOperationEntity::class,
        SyncConflictEntity::class, WashPostEntity::class, WashQueueItemEntity::class, WashTechCardEntity::class,
        WashChemicalUsageEntity::class, TireQueueItemEntity::class, TireDiagnosticEntity::class,
        TireWorkEntryEntity::class, TireStorageItemEntity::class, ServiceCatalogItemEntity::class,
        PriceListEntity::class, PriceListItemEntity::class, WorkOrderItemEntity::class,
    ],
    version = 13,
    exportSchema = true,
)
abstract class LexoraServiceDatabase : RoomDatabase() {
    abstract fun serviceDao(): ServiceDao
    abstract fun washDao(): WashDao
    abstract fun tireDao(): TireDao
    abstract fun catalogDao(): CatalogDao
    abstract fun workOrderDao(): WorkOrderDao

    companion object {
        private val MIGRATION_1_2 = object : Migration(1, 2) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("ALTER TABLE clients ADD COLUMN kpp TEXT"); db.execSQL("ALTER TABLE clients ADD COLUMN registrationAddress TEXT"); db.execSQL("ALTER TABLE clients ADD COLUMN actualAddress TEXT"); db.execSQL("ALTER TABLE clients ADD COLUMN note TEXT"); db.execSQL("ALTER TABLE clients ADD COLUMN consentPersonalData INTEGER NOT NULL DEFAULT 0") } }
        private val MIGRATION_2_3 = object : Migration(2, 3) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("ALTER TABLE vehicles ADD COLUMN bodyType TEXT"); db.execSQL("ALTER TABLE vehicles ADD COLUMN color TEXT"); db.execSQL("CREATE TABLE IF NOT EXISTS service_history (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, vehicleId TEXT NOT NULL, sourceType TEXT NOT NULL, sourceId TEXT, title TEXT NOT NULL, description TEXT, mileageKm INTEGER, occurredAtEpochMs INTEGER NOT NULL, createdAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_history_organizationId ON service_history(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_history_vehicleId ON service_history(vehicleId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_history_occurredAtEpochMs ON service_history(occurredAtEpochMs)") } }
        private val MIGRATION_3_4 = object : Migration(3, 4) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS service_objects (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, clientId TEXT, name TEXT NOT NULL, address TEXT, accessMode TEXT, responsibleContact TEXT, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_objects_organizationId ON service_objects(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_objects_clientId ON service_objects(clientId)"); db.execSQL("CREATE TABLE IF NOT EXISTS equipment (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, serviceObjectId TEXT, type TEXT NOT NULL, make TEXT, model TEXT, serialNumber TEXT, inventoryNumber TEXT, barcode TEXT, commissionedNote TEXT, warrantyNote TEXT, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_equipment_organizationId ON equipment(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_equipment_serviceObjectId ON equipment(serviceObjectId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_equipment_organizationId_serialNumber ON equipment(organizationId, serialNumber)") } }
        private val MIGRATION_4_5 = object : Migration(4, 5) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("ALTER TABLE branches ADD COLUMN phone TEXT"); db.execSQL("ALTER TABLE branches ADD COLUMN email TEXT"); db.execSQL("ALTER TABLE branches ADD COLUMN workSchedule TEXT"); db.execSQL("ALTER TABLE employees ADD COLUMN phone TEXT"); db.execSQL("ALTER TABLE employees ADD COLUMN email TEXT") } }
        private val MIGRATION_5_6 = object : Migration(5, 6) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS service_requests (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, number TEXT NOT NULL, clientId TEXT, vehicleId TEXT, serviceObjectId TEXT, equipmentId TEXT, branchId TEXT, assigneeEmployeeId TEXT, title TEXT NOT NULL, description TEXT, status TEXT NOT NULL, priority TEXT NOT NULL, plannedAtEpochMs INTEGER, dueAtEpochMs INTEGER, slaDeadlineEpochMs INTEGER, closedAtEpochMs INTEGER, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_requests_organizationId ON service_requests(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_requests_clientId ON service_requests(clientId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_requests_branchId ON service_requests(branchId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_requests_assigneeEmployeeId ON service_requests(assigneeEmployeeId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_requests_status ON service_requests(status)"); db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_service_requests_organizationId_number ON service_requests(organizationId, number)"); db.execSQL("CREATE TABLE IF NOT EXISTS request_status_history (id TEXT NOT NULL PRIMARY KEY, requestId TEXT NOT NULL, fromStatus TEXT, toStatus TEXT NOT NULL, changedByUserId TEXT NOT NULL, changedAtEpochMs INTEGER NOT NULL, comment TEXT)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_request_status_history_requestId ON request_status_history(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_request_status_history_changedAtEpochMs ON request_status_history(changedAtEpochMs)") } }
        private val MIGRATION_6_7 = object : Migration(6, 7) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS service_visits (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT NOT NULL, branchId TEXT, employeeId TEXT, status TEXT NOT NULL, plannedStartEpochMs INTEGER, plannedEndEpochMs INTEGER, actualStartEpochMs INTEGER, actualEndEpochMs INTEGER, resultNote TEXT, customerName TEXT, customerSignatureRef TEXT, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_visits_organizationId ON service_visits(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_visits_requestId ON service_visits(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_visits_employeeId ON service_visits(employeeId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_visits_status ON service_visits(status)"); db.execSQL("CREATE TABLE IF NOT EXISTS visit_checklist_items (id TEXT NOT NULL PRIMARY KEY, visitId TEXT NOT NULL, title TEXT NOT NULL, state TEXT NOT NULL, comment TEXT, sortOrder INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_visit_checklist_items_visitId ON visit_checklist_items(visitId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_visit_checklist_items_sortOrder ON visit_checklist_items(sortOrder)"); db.execSQL("CREATE TABLE IF NOT EXISTS visit_work_entries (id TEXT NOT NULL PRIMARY KEY, visitId TEXT NOT NULL, serviceCode TEXT, title TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT, note TEXT, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_visit_work_entries_visitId ON visit_work_entries(visitId)"); db.execSQL("CREATE TABLE IF NOT EXISTS visit_material_usage (id TEXT NOT NULL PRIMARY KEY, visitId TEXT NOT NULL, materialCode TEXT, title TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT, note TEXT, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_visit_material_usage_visitId ON visit_material_usage(visitId)"); db.execSQL("CREATE TABLE IF NOT EXISTS visit_photos (id TEXT NOT NULL PRIMARY KEY, visitId TEXT NOT NULL, localUri TEXT NOT NULL, caption TEXT, takenAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_visit_photos_visitId ON visit_photos(visitId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_visit_photos_takenAtEpochMs ON visit_photos(takenAtEpochMs)") } }
        private val MIGRATION_7_8 = object : Migration(7, 8) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS service_documents (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, visitId TEXT, clientId TEXT, type TEXT NOT NULL, number TEXT NOT NULL, status TEXT NOT NULL, issuedAtEpochMs INTEGER, totalMinor INTEGER NOT NULL, currency TEXT NOT NULL, externalFileRef TEXT, note TEXT, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_documents_organizationId ON service_documents(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_documents_requestId ON service_documents(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_documents_visitId ON service_documents(visitId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_documents_clientId ON service_documents(clientId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_service_documents_type ON service_documents(type)"); db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_service_documents_organizationId_number ON service_documents(organizationId, number)"); db.execSQL("CREATE TABLE IF NOT EXISTS payments (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, documentId TEXT, clientId TEXT, amountMinor INTEGER NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, method TEXT NOT NULL, paidAtEpochMs INTEGER, externalReference TEXT, note TEXT, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_payments_organizationId ON payments(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_payments_requestId ON payments(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_payments_documentId ON payments(documentId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_payments_clientId ON payments(clientId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_payments_status ON payments(status)") } }
        private val MIGRATION_8_9 = object : Migration(8, 9) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS sync_operations (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, entityType TEXT NOT NULL, entityId TEXT NOT NULL, operationType TEXT NOT NULL, idempotencyKey TEXT NOT NULL, payloadJson TEXT, status TEXT NOT NULL, attemptCount INTEGER NOT NULL, nextAttemptAtEpochMs INTEGER, lastError TEXT, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_operations_organizationId ON sync_operations(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_operations_entityType ON sync_operations(entityType)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_operations_entityId ON sync_operations(entityId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_operations_status ON sync_operations(status)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_operations_nextAttemptAtEpochMs ON sync_operations(nextAttemptAtEpochMs)"); db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_sync_operations_organizationId_idempotencyKey ON sync_operations(organizationId, idempotencyKey)"); db.execSQL("CREATE TABLE IF NOT EXISTS sync_conflicts (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, entityType TEXT NOT NULL, entityId TEXT NOT NULL, localVersionJson TEXT, remoteVersionJson TEXT, resolution TEXT NOT NULL, detectedAtEpochMs INTEGER NOT NULL, resolvedAtEpochMs INTEGER)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_conflicts_organizationId ON sync_conflicts(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_conflicts_entityType ON sync_conflicts(entityType)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_conflicts_entityId ON sync_conflicts(entityId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_conflicts_resolution ON sync_conflicts(resolution)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_sync_conflicts_detectedAtEpochMs ON sync_conflicts(detectedAtEpochMs)") } }
        private val MIGRATION_9_10 = object : Migration(9, 10) { override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL("CREATE TABLE IF NOT EXISTS wash_posts (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, branchId TEXT, name TEXT NOT NULL, status TEXT NOT NULL, active INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_posts_organizationId ON wash_posts(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_posts_branchId ON wash_posts(branchId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_posts_status ON wash_posts(status)");
            db.execSQL("CREATE TABLE IF NOT EXISTS wash_queue (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, vehicleId TEXT, postId TEXT, position INTEGER NOT NULL, status TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_organizationId ON wash_queue(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_requestId ON wash_queue(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_vehicleId ON wash_queue(vehicleId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_postId ON wash_queue(postId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_status ON wash_queue(status)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_position ON wash_queue(position)");
            db.execSQL("CREATE TABLE IF NOT EXISTS wash_tech_cards (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, name TEXT NOT NULL, durationMinutes INTEGER NOT NULL, stepsText TEXT NOT NULL, active INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_tech_cards_organizationId ON wash_tech_cards(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_tech_cards_active ON wash_tech_cards(active)");
            db.execSQL("CREATE TABLE IF NOT EXISTS wash_chemical_usage (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, postId TEXT, chemicalName TEXT NOT NULL, quantityMl REAL NOT NULL, usedAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_chemical_usage_organizationId ON wash_chemical_usage(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_chemical_usage_requestId ON wash_chemical_usage(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_chemical_usage_postId ON wash_chemical_usage(postId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_chemical_usage_usedAtEpochMs ON wash_chemical_usage(usedAtEpochMs)")
        } }
        private val MIGRATION_10_11 = object : Migration(10, 11) { override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL("CREATE TABLE IF NOT EXISTS tire_queue (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, vehicleId TEXT, position INTEGER NOT NULL, status TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_queue_organizationId ON tire_queue(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_queue_requestId ON tire_queue(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_queue_vehicleId ON tire_queue(vehicleId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_queue_status ON tire_queue(status)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_queue_position ON tire_queue(position)");
            db.execSQL("CREATE TABLE IF NOT EXISTS tire_diagnostics (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, vehicleId TEXT, pressureNote TEXT, treadDepthMm REAL, damageNote TEXT, recommendation TEXT, diagnosedAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_diagnostics_organizationId ON tire_diagnostics(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_diagnostics_requestId ON tire_diagnostics(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_diagnostics_vehicleId ON tire_diagnostics(vehicleId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_diagnostics_diagnosedAtEpochMs ON tire_diagnostics(diagnosedAtEpochMs)");
            db.execSQL("CREATE TABLE IF NOT EXISTS tire_work_entries (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, vehicleId TEXT, title TEXT NOT NULL, quantity REAL NOT NULL, note TEXT, performedAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_work_entries_organizationId ON tire_work_entries(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_work_entries_requestId ON tire_work_entries(requestId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_work_entries_vehicleId ON tire_work_entries(vehicleId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_work_entries_performedAtEpochMs ON tire_work_entries(performedAtEpochMs)");
            db.execSQL("CREATE TABLE IF NOT EXISTS tire_storage (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, clientId TEXT, vehicleId TEXT, storageCode TEXT NOT NULL, tireDescription TEXT NOT NULL, quantity INTEGER NOT NULL, location TEXT, status TEXT NOT NULL, storedAtEpochMs INTEGER NOT NULL, issuedAtEpochMs INTEGER, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_storage_organizationId ON tire_storage(organizationId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_storage_clientId ON tire_storage(clientId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_storage_vehicleId ON tire_storage(vehicleId)"); db.execSQL("CREATE INDEX IF NOT EXISTS index_tire_storage_status ON tire_storage(status)"); db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_tire_storage_organizationId_storageCode ON tire_storage(organizationId, storageCode)")
        } }
        private val MIGRATION_11_12 = object : Migration(11, 12) { override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL("CREATE TABLE IF NOT EXISTS service_catalog (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, code TEXT NOT NULL, name TEXT NOT NULL, category TEXT, unit TEXT NOT NULL, durationMinutes INTEGER, active INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_service_catalog_organizationId ON service_catalog(organizationId)")
            db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_service_catalog_organizationId_code ON service_catalog(organizationId, code)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_service_catalog_active ON service_catalog(active)")
            db.execSQL("CREATE TABLE IF NOT EXISTS price_lists (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, name TEXT NOT NULL, currency TEXT NOT NULL, effectiveFromEpochMs INTEGER NOT NULL, effectiveToEpochMs INTEGER, active INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_price_lists_organizationId ON price_lists(organizationId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_price_lists_active ON price_lists(active)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_price_lists_effectiveFromEpochMs ON price_lists(effectiveFromEpochMs)")
            db.execSQL("CREATE TABLE IF NOT EXISTS price_list_items (id TEXT NOT NULL PRIMARY KEY, priceListId TEXT NOT NULL, serviceCatalogItemId TEXT NOT NULL, priceMinor INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_price_list_items_priceListId ON price_list_items(priceListId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_price_list_items_serviceCatalogItemId ON price_list_items(serviceCatalogItemId)")
            db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_price_list_items_priceListId_serviceCatalogItemId ON price_list_items(priceListId, serviceCatalogItemId)")
        } }
        private val MIGRATION_12_13 = object : Migration(12, 13) { override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL("CREATE TABLE IF NOT EXISTS work_order_items (id TEXT NOT NULL PRIMARY KEY, documentId TEXT NOT NULL, serviceCatalogItemId TEXT, title TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT NOT NULL, unitPriceMinor INTEGER NOT NULL, totalMinor INTEGER NOT NULL, additional INTEGER NOT NULL, approvalStatus TEXT NOT NULL, approvalComment TEXT, approvedAtEpochMs INTEGER, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_work_order_items_documentId ON work_order_items(documentId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_work_order_items_serviceCatalogItemId ON work_order_items(serviceCatalogItemId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS index_work_order_items_approvalStatus ON work_order_items(approvalStatus)")
        } }

        fun create(context: Context): LexoraServiceDatabase = Room.databaseBuilder(context.applicationContext, LexoraServiceDatabase::class.java, "lexora-service.db").addMigrations(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4, MIGRATION_4_5, MIGRATION_5_6, MIGRATION_6_7, MIGRATION_7_8, MIGRATION_8_9, MIGRATION_9_10, MIGRATION_10_11, MIGRATION_11_12, MIGRATION_12_13).build()
    }
}
