package com.lexora.service.core.database

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(
    entities = [OrganizationEntity::class, ClientEntity::class, VehicleEntity::class, BranchEntity::class, EmployeeEntity::class, ModuleSettingEntity::class, AuditEventEntity::class, ServiceHistoryEntity::class, ServiceObjectEntity::class, EquipmentEntity::class, ServiceRequestEntity::class, RequestStatusHistoryEntity::class, ServiceVisitEntity::class, VisitChecklistItemEntity::class, VisitWorkEntryEntity::class, VisitMaterialUsageEntity::class, VisitPhotoEntity::class, ServiceDocumentEntity::class, PaymentEntity::class, SyncOperationEntity::class, SyncConflictEntity::class, WashPostEntity::class, WashQueueItemEntity::class, WashTechCardEntity::class, WashChemicalUsageEntity::class],
    version = 10,
    exportSchema = true,
)
abstract class LexoraServiceDatabase : RoomDatabase() {
    abstract fun serviceDao(): ServiceDao

    companion object {
        private val MIGRATION_1_2 = object : Migration(1, 2) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("ALTER TABLE clients ADD COLUMN kpp TEXT"); db.execSQL("ALTER TABLE clients ADD COLUMN registrationAddress TEXT"); db.execSQL("ALTER TABLE clients ADD COLUMN actualAddress TEXT"); db.execSQL("ALTER TABLE clients ADD COLUMN note TEXT"); db.execSQL("ALTER TABLE clients ADD COLUMN consentPersonalData INTEGER NOT NULL DEFAULT 0") } }
        private val MIGRATION_2_3 = object : Migration(2, 3) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("ALTER TABLE vehicles ADD COLUMN bodyType TEXT"); db.execSQL("ALTER TABLE vehicles ADD COLUMN color TEXT"); db.execSQL("CREATE TABLE IF NOT EXISTS service_history (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, vehicleId TEXT NOT NULL, sourceType TEXT NOT NULL, sourceId TEXT, title TEXT NOT NULL, description TEXT, mileageKm INTEGER, occurredAtEpochMs INTEGER NOT NULL, createdAtEpochMs INTEGER NOT NULL)") } }
        private val MIGRATION_3_4 = object : Migration(3, 4) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS service_objects (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, clientId TEXT, name TEXT NOT NULL, address TEXT, accessMode TEXT, responsibleContact TEXT, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE TABLE IF NOT EXISTS equipment (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, serviceObjectId TEXT, type TEXT NOT NULL, make TEXT, model TEXT, serialNumber TEXT, inventoryNumber TEXT, barcode TEXT, commissionedNote TEXT, warrantyNote TEXT, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)") } }
        private val MIGRATION_4_5 = object : Migration(4, 5) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("ALTER TABLE branches ADD COLUMN phone TEXT"); db.execSQL("ALTER TABLE branches ADD COLUMN email TEXT"); db.execSQL("ALTER TABLE branches ADD COLUMN workSchedule TEXT"); db.execSQL("ALTER TABLE employees ADD COLUMN phone TEXT"); db.execSQL("ALTER TABLE employees ADD COLUMN email TEXT") } }
        private val MIGRATION_5_6 = object : Migration(5, 6) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS service_requests (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, number TEXT NOT NULL, clientId TEXT, vehicleId TEXT, serviceObjectId TEXT, equipmentId TEXT, branchId TEXT, assigneeEmployeeId TEXT, title TEXT NOT NULL, description TEXT, status TEXT NOT NULL, priority TEXT NOT NULL, plannedAtEpochMs INTEGER, dueAtEpochMs INTEGER, slaDeadlineEpochMs INTEGER, closedAtEpochMs INTEGER, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE TABLE IF NOT EXISTS request_status_history (id TEXT NOT NULL PRIMARY KEY, requestId TEXT NOT NULL, fromStatus TEXT, toStatus TEXT NOT NULL, changedByUserId TEXT NOT NULL, changedAtEpochMs INTEGER NOT NULL, comment TEXT)") } }
        private val MIGRATION_6_7 = object : Migration(6, 7) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS service_visits (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT NOT NULL, branchId TEXT, employeeId TEXT, status TEXT NOT NULL, plannedStartEpochMs INTEGER, plannedEndEpochMs INTEGER, actualStartEpochMs INTEGER, actualEndEpochMs INTEGER, resultNote TEXT, customerName TEXT, customerSignatureRef TEXT, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE TABLE IF NOT EXISTS visit_checklist_items (id TEXT NOT NULL PRIMARY KEY, visitId TEXT NOT NULL, title TEXT NOT NULL, state TEXT NOT NULL, comment TEXT, sortOrder INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE TABLE IF NOT EXISTS visit_work_entries (id TEXT NOT NULL PRIMARY KEY, visitId TEXT NOT NULL, serviceCode TEXT, title TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT, note TEXT, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE TABLE IF NOT EXISTS visit_material_usage (id TEXT NOT NULL PRIMARY KEY, visitId TEXT NOT NULL, materialCode TEXT, title TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT, note TEXT, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE TABLE IF NOT EXISTS visit_photos (id TEXT NOT NULL PRIMARY KEY, visitId TEXT NOT NULL, localUri TEXT NOT NULL, caption TEXT, takenAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)") } }
        private val MIGRATION_7_8 = object : Migration(7, 8) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS service_documents (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, visitId TEXT, clientId TEXT, type TEXT NOT NULL, number TEXT NOT NULL, status TEXT NOT NULL, issuedAtEpochMs INTEGER, totalMinor INTEGER NOT NULL, currency TEXT NOT NULL, externalFileRef TEXT, note TEXT, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE TABLE IF NOT EXISTS payments (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, documentId TEXT, clientId TEXT, amountMinor INTEGER NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, method TEXT NOT NULL, paidAtEpochMs INTEGER, externalReference TEXT, note TEXT, archived INTEGER NOT NULL, syncState TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)") } }
        private val MIGRATION_8_9 = object : Migration(8, 9) { override fun migrate(db: SupportSQLiteDatabase) { db.execSQL("CREATE TABLE IF NOT EXISTS sync_operations (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, entityType TEXT NOT NULL, entityId TEXT NOT NULL, operationType TEXT NOT NULL, idempotencyKey TEXT NOT NULL, payloadJson TEXT, status TEXT NOT NULL, attemptCount INTEGER NOT NULL, nextAttemptAtEpochMs INTEGER, lastError TEXT, createdAtEpochMs INTEGER NOT NULL, updatedAtEpochMs INTEGER NOT NULL)"); db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_sync_operations_organizationId_idempotencyKey ON sync_operations(organizationId,idempotencyKey)"); db.execSQL("CREATE TABLE IF NOT EXISTS sync_conflicts (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, entityType TEXT NOT NULL, entityId TEXT NOT NULL, localVersionJson TEXT, remoteVersionJson TEXT, resolution TEXT NOT NULL, detectedAtEpochMs INTEGER NOT NULL, resolvedAtEpochMs INTEGER)") } }
        private val MIGRATION_9_10 = object : Migration(9, 10) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("CREATE TABLE IF NOT EXISTS wash_posts (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, branchId TEXT, name TEXT NOT NULL, status TEXT NOT NULL, active INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_posts_organizationId ON wash_posts(organizationId)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_posts_branchId ON wash_posts(branchId)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_posts_status ON wash_posts(status)")
                db.execSQL("CREATE TABLE IF NOT EXISTS wash_queue (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, vehicleId TEXT, postId TEXT, position INTEGER NOT NULL, status TEXT NOT NULL, createdAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_organizationId ON wash_queue(organizationId)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_status ON wash_queue(status)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_queue_position ON wash_queue(position)")
                db.execSQL("CREATE TABLE IF NOT EXISTS wash_tech_cards (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, name TEXT NOT NULL, durationMinutes INTEGER NOT NULL, stepsText TEXT NOT NULL, active INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_tech_cards_organizationId ON wash_tech_cards(organizationId)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_tech_cards_active ON wash_tech_cards(active)")
                db.execSQL("CREATE TABLE IF NOT EXISTS wash_chemical_usage (id TEXT NOT NULL PRIMARY KEY, organizationId TEXT NOT NULL, requestId TEXT, postId TEXT, chemicalName TEXT NOT NULL, quantityMl REAL NOT NULL, usedAtEpochMs INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAtEpochMs INTEGER NOT NULL)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_chemical_usage_organizationId ON wash_chemical_usage(organizationId)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_wash_chemical_usage_usedAtEpochMs ON wash_chemical_usage(usedAtEpochMs)")
            }
        }

        fun create(context: Context): LexoraServiceDatabase = Room.databaseBuilder(context.applicationContext, LexoraServiceDatabase::class.java, "lexora-service.db").addMigrations(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4, MIGRATION_4_5, MIGRATION_5_6, MIGRATION_6_7, MIGRATION_7_8, MIGRATION_8_9, MIGRATION_9_10).build()
    }
}
